#! /bin/sh

LOG_FILE=$HOME/.config/bspwm/bspwm.log
CONFIG_DIR=$HOME/.config

echo "===========================" >> "$LOG_FILE" 
date >> "$LOG_FILE"

# HDMI-A-0 monitor on top of eDP monitor
xrandr --output HDMI-A-0 --above eDP --mode 1366x768 --output eDP --mode 1280x720
#xrandr --output HDMI-A-0 

# Baja el brillo
brightnessctl s 0%

"$CONFIG_DIR"/sxhkd/launch.sh
"$CONFIG_DIR"/picom/launch.sh
"$CONFIG_DIR"/nitrogen/launch.sh
"$CONFIG_DIR"/polybar/launch.sh

# BSPWM
if xrandr | grep "HDMI-A-0" >/dev/null; then
    echo "Se se encontro HDMI-A-0" >> "$LOG_FILE"
    bspc monitor eDP -d VI VII VIII IX X
    bspc monitor HDMI-A-0 -d I II III IV V
else
    echo "No se encontro HDMI-A-0" >> "$LOG_FILE"
    bspc monitor eDP -d I II III IV V VI VII VIII IX X
fi


bspc config border_width         3
bspc config window_gap           0

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a '*' border=off
bspc rule -a focused border=on

bspc rule -a Code          desktop='I'  state=tiled follow=on
bspc rule -a Google-chrome desktop='II' state=tiled follow=on
bspc rule -a kitty         desktop='IV' state=tiled follow=on
